verbose: false
instrumentation:
    root: ./
    includes: ['src/**/*.js', 'commands/**/*.js']
    excludes: ['node-modules/*', 'lib/*', 'webpack.config.js']
    include-all-sources: true
    es-modules: true
reporting:
hooks:
check:
