site_name: Ranvier
site_description: NodeJS based MUD engine
copyright: Copyright &copy; 2017, Shawn Biddle
site_author: Shawn Biddle
docs_dir: docs
repo_url: https://github.com/shawncplus/ranviermud
theme: null
theme_dir: docs_theme/ranvier
extra:
    logo: '_static/images/logo.png'
markdown_extensions:
    - def_list
    - toc:
        permalink: true

pages:

- Overview: index.md
- Get Started: get_started.md
- Project Structure: structure.md
